version: '3'
name: teletoobit

services:

  puller:
    container_name: tg_puller
    build: ./puller
    env_file:
      - ./puller/.env
    restart: always
    networks:
      - my_bridge
    environment:
      - MONGODB_URL=mongodb://mongo_user:mongo_pass@mongodb:27017/tg?authSource=admin

  bot:
    container_name: tg_bot
    build: ./bot
    env_file:
      - ./bot/.env
    restart: always
    networks:
      - my_bridge
    environment:
      - MONGODB_URL=mongodb://mongo_user:mongo_pass@mongodb:27017/tg?authSource=admin

  mongodb:
    image: mongo:6.0
    container_name: tg_mongodb
    restart: unless-stopped
    ports:
      - "3000:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: tg
    networks:
      - my_bridge

volumes:
  mongodb_data:


networks:
  my_bridge:
    driver: bridge
